include "exploresensor.inc"

# You may edit the definition of robot_ranger.  
# You can change the position and direction of the exploresensors,
# add additional exploresensors or remove exploresensors.  Your 
# robot may possess up to 16 exploresensors (not more).  Do not
# remove the include line.

define robot_ranger ranger 
(
   exploresensor ( pose [ 0  0 0.1   0] )
   exploresensor ( pose [ 0  0 0.1   7] )
   exploresensor ( pose [ 0  0 0.1  15] )
   exploresensor ( pose [ 0  0 0.1  22] )
   exploresensor ( pose [ 0  0 0.1  30] )
   exploresensor ( pose [ 0  0 0.1  60] )  
   exploresensor ( pose [ 0  0 0.1  90] )
   exploresensor ( pose [ 0  0 0.1 135] )
   exploresensor ( pose [ 0  0 0.1 180] )
   exploresensor ( pose [ 0  0 0.1 225] )
   exploresensor ( pose [ 0  0 0.1 270] )
   exploresensor ( pose [ 0  0 0.1 300] )
   exploresensor ( pose [ 0  0 0.1 330] )
   exploresensor ( pose [ 0  0 0.1 338] ) 
   exploresensor ( pose [ 0  0 0.1 345] ) 
   exploresensor ( pose [ 0  0 0.1 353] )
  
)
